In [17]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df=pd.read_csv(r'C:\Users\prakh\Downloads\Titanic-Dataset.csv')

In [4]:
df.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
df.isnull().sum()#or df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
#Data Cleaning 
df.drop('PassengerId',inplace=True,axis=1)

In [9]:
df['Cabin'].count()/df.shape[0]

0.22895622895622897

In [10]:
df.drop('Cabin',inplace=True,axis=1)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 69.7+ KB

In [12]:
df['Age'].count()/df.shape[0]

0.8013468013468014

In [13]:
df.dropna(subset=['Age','Embarked'],inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  712 non-null    int64
 1   Pclass    712 non-null    int64
 2   Name      712 non-null    object
 3   Sex       712 non-null    object
 4   Age       712 non-null    float64
 5   SibSp     712 non-null    int64
 6   Parch     712 non-null    int64
 7   Ticket    712 non-null    object
 8   Fare      712 non-null    float64
 9   Embarked  712 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 61.2+ KB

In [15]:
df['Title']=df['Name'].str.extract(r'([A-Za-z]+\.)',expand=False)
df.drop('Name',inplace=True,axis=1)

In [16]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Title
0,0,3,male,22.00,1,0,A/5 21171,7.2500,S,Mr.
1,1,1,female,38.00,1,0,PC 17599,71.2833,C,Mrs.
2,1,3,female,26.00,0,0,STON/O2. 3101282,7.9250,S,Miss.
3,1,1,female,35.00,1,0,113803,53.1000,S,Mrs.
4,0,3,male,35.00,0,0,373450,8.0500,S,Mr.
6,0,1,male,54.00,0,0,17463,51.8625,S,Mr.
7,0,3,male,2.00,3,1,349909,21.0750,S,Master.
8,1,3,female,27.00,0,2,347742,11.1333,S,Mrs.
9,1,2,female,14.00,1,0,237736,30.0708,C,Mrs.
10,1,3,female,4.00,1,1,PP 9549,16.7000,S,Miss.
11,1,1,female,58.00,0,0,113783,26.5500,S,Miss.
12,0,3,male,20.00,0,0,A/5. 2151,8.0500,S,Mr.
13,0,3,male,39.00,1,5,347082,31.2750,S,Mr.
14,0,3,female,14.00,0,0,350406,7.8542,S,Miss.
15,1,2,female,55.00,0,0,248706,16.0000,S,Mrs.
16,0,3,male,2.00,4,1,382652,29.1250,Q,Master.
18,0,3,female,31.00,1,0,345763,18.0000,S,Mrs.
20,0,2,male,35.00,0,0,239865,26.0000,S,Mr.
21,1,2,male,34.00,0,0,248698,13.0000,S,Mr.
22,1,3,female,15.00,0,0,330923,8.0292,Q,Miss.
23,1,1,male,28.00,0,0,113788,35.5000,S,Mr.
24,0,3,female,8.00,3,1,349909,21.0750,S,Miss.
25,1,3,female,38.00,1,5,347077,31.3875,S,Mrs.
27,0,1,male,19.00,3,2,19950,263.0000,S,Mr.
30,0,1,male,40.00,0,0,PC 17601,27.7208,C,Don.
33,0,2,male,66.00,0,0,C.A. 24579,10.5000,S,Mr.
34,0,1,male,28.00,1,0,PC 17604,82.1708,C,Mr.
35,0,1,male,42.00,1,0,113789,52.0000,S,Mr.
37,0,3,male,21.00,0,0,A./5. 2152,8.0500,S,Mr.
38,0,3,female,18.00,2,0,345764,18.0000,S,Miss.
39,1,3,female,14.00,1,0,2651,11.2417,C,Miss.
40,0,3,female,40.00,1,0,7546,9.4750,S,Mrs.
41,0,2,female,27.00,1,0,11668,21.0000,S,Mrs.
43,1,2,female,3.00,1,2,SC/Paris 2123,41.5792,C,Miss.
44,1,3,female,19.00,0,0,330958,7.8792,Q,Miss.
49,0,3,female,18.00,1,0,349237,17.8000,S,Mrs.
50,0,3,male,7.00,4,1,3101295,39.6875,S,Master.
51,0,3,male,21.00,0,0,A/4. 39886,7.8000,S,Mr.
52,1,1,female,49.00,1,0,PC 17572,76.7292,C,Mrs.
53,1,2,female,29.00,1,0,2926,26.0000,S,Mrs.
54,0,1,male,65.00,0,1,113509,61.9792,C,Mr.
56,1,2,female,21.00,0,0,C.A. 31026,10.5000,S,Miss.
57,0,3,male,28.50,0,0,2697,7.2292,C,Mr.
58,1,2,female,5.00,1,2,C.A. 34651,27.7500,S,Miss.
59,0,3,male,11.00,5,2,CA 2144,46.9000,S,Master.
60,0,3,male,22.00,0,0,2669,7.2292,C,Mr.
62,0,1,male,45.00,1,0,36973,83.4750,S,Mr.
63,0,3,male,4.00,3,2,347088,27.9000,S,Master.
66,1,2,female,29.00,0,0,C.A. 29395,10.5000,S,Mrs.
67,0,3,male,19.00,0,0,S.P. 3464,8.1583,S,Mr.
68,1,3,female,17.00,4,2,3101281,7.9250,S,Miss.
69,0,3,male,26.00,2,0,315151,8.6625,S,Mr.
70,0,2,male,32.00,0,0,C.A. 33111,10.5000,S,Mr.
71,0,3,female,16.00,5,2,CA 2144,46.9000,S,Miss.
72,0,2,male,21.00,0,0,S.O.C. 14879,73.5000,S,Mr.
73,0,3,male,26.00,1,0,2680,14.4542,C,Mr.
74,1,3,male,32.00,0,0,1601,56.4958,S,Mr.
75,0,3,male,25.00,0,0,348123,7.6500,S,Mr.
78,1,2,male,0.83,0,2,248738,29.0000,S,Master.
79,1,3,female,30.00,0,0,364516,12.4750,S,Miss.
80,0,3,male,22.00,0,0,345767,9.0000,S,Mr.
81,1,3,male,29.00,0,0,345779,9.5000,S,Mr.
83,0,1,male,28.00,0,0,113059,47.1000,S,Mr.
84,1,2,female,17.00,0,0,SO/C 14885,10.5000,S,Miss.
85,1,3,female,33.00,3,0,3101278,15.8500,S,Mrs.
86,0,3,male,16.00,1,3,W./C. 6608,34.3750,S,Mr.
88,1,1,female,23.00,3,2,19950,263.0000,S,Miss.
89,0,3,male,24.00,0,0,343275,8.0500,S,Mr.
90,0,3,male,29.00,0,0,343276,8.0500,S,Mr.
91,0,3,male,20.00,0,0,347466,7.8542,S,Mr.
92,0,1,male,46.00,1,0,W.E.P. 5734,61.1750,S,Mr.
93,0,3,male,26.00,1,2,C.A. 2315,20.5750,S,Mr.
94,0,3,male,59.00,0,0,364500,7.2500,S,Mr.
96,0,1,male,71.00,0,0,PC 17754,34.6542,C,Mr.
97,1,1,male,23.00,0,1,PC 17759,63.3583,C,Mr.
98,1,2,female,34.00,0,1,231919,23.0000,S,Mrs.
99,0,2,male,34.00,1,0,244367,26.0000,S,Mr.
100,0,3,female,28.00,0,0,349245,7.8958,S,Miss.
102,0,1,male,21.00,0,1,35281,77.2875,S,Mr.
103,0,3,male,33.00,0,0,7540,8.6542,S,Mr.
104,0,3,male,37.00,2,0,3101276,7.9250,S,Mr.
105,0,3,male,28.00,0,0,349207,7.8958,S,Mr.
106,1,3,female,21.00,0,0,343120,7.6500,S,Miss.
108,0,3,male,38.00,0,0,349249,7.8958,S,Mr.
110,0,1,male,47.00,0,0,110465,52.0000,S,Mr.
111,0,3,female,14.50,1,0,2665,14.4542,C,Miss.
112,0,3,male,22.00,0,0,324669,8.0500,S,Mr.
113,0,3,female,20.00,1,0,4136,9.8250,S,Miss.
114,0,3,female,17.00,0,0,2627,14.4583,C,Miss.
115,0,3,male,21.00,0,0,STON/O 2. 3101294,7.9250,S,Mr.
116,0,3,male,70.50,0,0,370369,7.7500,Q,Mr.
117,0,2,male,29.00,1,0,11668,21.0000,S,Mr.
118,0,1,male,24.00,0,1,PC 17558,247.5208,C,Mr.
119,0,3,female,2.00,4,2,347082,31.2750,S,Miss.
120,0,2,male,21.00,2,0,S.O.C. 14879,73.5000,S,Mr.
122,0,2,male,32.50,1,0,237736,30.0708,C,Mr.
123,1,2,female,32.50,0,0,27267,13.0000,S,Miss.
124,0,1,male,54.00,0,1,35281,77.2875,S,Mr.
125,1,3,male,12.00,1,0,2651,11.2417,C,Master.
127,1,3,male,24.00,0,0,C 17369,7.1417,S,Mr.
129,0,3,male,45.00,0,0,347061,6.9750,S,Mr.
130,0,3,male,33.00,0,0,349241,7.8958,C,Mr.
131,0,3,male,20.00,0,0,SOTON/O.Q. 3101307,7.0500,S,Mr.
132,0,3,female,47.00,1,0,A/5. 3337,14.5000,S,Mrs.
133,1,2,female,29.00,1,0,228414,26.0000,S,Mrs.
134,0,2,male,25.00,0,0,C.A. 29178,13.0000,S,Mr.
135,0,2,male,23.00,0,0,SC/PARIS 2133,15.0458,C,Mr.
136,1,1,female,19.00,0,2,11752,26.2833,S,Miss.
137,0,1,male,37.00,1,0,113803,53.1000,S,Mr.
138,0,3,male,16.00,0,0,7534,9.2167,S,Mr.
139,0,1,male,24.00,0,0,PC 17593,79.2000,C,Mr.
141,1,3,female,22.00,0,0,347081,7.7500,S,Miss.
142,1,3,female,24.00,1,0,STON/O2. 3101279,15.8500,S,Mrs.
143,0,3,male,19.00,0,0,365222,6.7500,Q,Mr.
144,0,2,male,18.00,0,0,231945,11.5000,S,Mr.
145,0,2,male,19.00,1,1,C.A. 33112,36.7500,S,Mr.
146,1,3,male,27.00,0,0,350043,7.7958,S,Mr.
147,0,3,female,9.00,2,2,W./C. 6608,34.3750,S,Miss.
148,0,2,male,36.50,0,2,230080,26.0000,S,Mr.
149,0,2,male,42.00,0,0,244310,13.0000,S,Rev.
150,0,2,male,51.00,0,0,S.O.P. 1166,12.5250,S,Rev.
151,1,1,female,22.00,1,0,113776,66.6000,S,Mrs.
152,0,3,male,55.50,0,0,A.5. 11206,8.0500,S,Mr.
153,0,3,male,40.50,0,2,A/5. 851,14.5000,S,Mr.
155,0,1,male,51.00,0,1,PC 17597,61.3792,C,Mr.
156,1,3,female,16.00,0,0,35851,7.7333,Q,Miss.
157,0,3,male,30.00,0,0,SOTON/OQ 392090,8.0500,S,Mr.
160,0,3,male,44.00,0,1,371362,16.1000,S,Mr.
161,1,2,female,40.00,0,0,C.A. 33595,15.7500,S,Mrs.
162,0,3,male,26.00,0,0,347068,7.7750,S,Mr.
163,0,3,male,17.00,0,0,315093,8.6625,S,Mr.
164,0,3,male,1.00,4,1,3101295,39.6875,S,Master.
165,1,3,male,9.00,0,2,363291,20.5250,S,Master.
167,0,3,female,45.00,1,4,347088,27.9000,S,Mrs.
169,0,3,male,28.00,0,0,1601,56.4958,S,Mr.
170,0,1,male,61.00,0,0,111240,33.5000,S,Mr.
171,0,3,male,4.00,4,1,382652,29.1250,Q,Master.
172,1,3,female,1.00,1,1,347742,11.1333,S,Miss.
173,0,3,male,21.00,0,0,STON/O 2. 3101280,7.9250,S,Mr.
174,0,1,male,56.00,0,0,17764,30.6958,C,Mr.
175,0,3,male,18.00,1,1,350404,7.8542,S,Mr.
177,0,1,female,50.00,0,0,PC 17595,28.7125,C,Miss.
178,0,2,male,30.00,0,0,250653,13.0000,S,Mr.
179,0,3,male,36.00,0,0,LINE,0.0000,S,Mr.
182,0,3,male,9.00,4,2,347077,31.3875,S,Master.
183,1,2,male,1.00,2,1,230136,39.0000,S,Master.
184,1,3,female,4.00,0,2,315153,22.0250,S,Miss.
187,1,1,male,45.00,0,0,111428,26.5500,S,Mr.
188,0,3,male,40.00,1,1,364849,15.5000,Q,Mr.
189,0,3,male,36.00,0,0,349247,7.8958,S,Mr.
190,1,2,female,32.00,0,0,234604,13.0000,S,Mrs.
191,0,2,male,19.00,0,0,28424,13.0000,S,Mr.
192,1,3,female,19.00,1,0,350046,7.8542,S,Miss.
193,1,2,male,3.00,1,1,230080,26.0000,S,Master.
194,1,1,female,44.00,0,0,PC 17610,27.7208,C,Mrs.
195,1,1,female,58.00,0,0,PC 17569,146.5208,C,Miss.
197,0,3,male,42.00,0,1,4579,8.4042,S,Mr.
199,0,2,female,24.00,0,0,248747,13.0000,S,Miss.
200,0,3,male,28.00,0,0,345770,9.5000,S,Mr.
202,0,3,male,34.00,0,0,3101264,6.4958,S,Mr.
203,0,3,male,45.50,0,0,2628,7.2250,C,Mr.
204,1,3,male,18.00,0,0,A/5 3540,8.0500,S,Mr.
205,0,3,female,2.00,0,1,347054,10.4625,S,Miss.
206,0,3,male,32.00,1,0,3101278,15.8500,S,Mr.
207,1,3,male,26.00,0,0,2699,18.7875,C,Mr.
208,1,3,female,16.00,0,0,367231,7.7500,Q,Miss.
209,1,1,male,40.00,0,0,112277,31.0000,C,Mr.
210,0,3,male,24.00,0,0,SOTON/O.Q. 3101311,7.0500,S,Mr.
211,1,2,female,35.00,0,0,F.C.C. 13528,21.0000,S,Miss.
212,0,3,male,22.00,0,0,A/5 21174,7.2500,S,Mr.
213,0,2,male,30.00,0,0,250646,13.0000,S,Mr.
215,1,1,female,31.00,1,0,35273,113.2750,C,Miss.
216,1,3,female,27.00,0,0,STON/O2. 3101283,7.9250,S,Miss.
217,0,2,male,42.00,1,0,243847,27.0000,S,Mr.
218,1,1,female,32.00,0,0,11813,76.2917,C,Miss.
219,0,2,male,30.00,0,0,W/C 14208,10.5000,S,Mr.
220,1,3,male,16.00,0,0,SOTON/OQ 392089,8.0500,S,Mr.
221,0,2,male,27.00,0,0,220367,13.0000,S,Mr.
222,0,3,male,51.00,0,0,21440,8.0500,S,Mr.
224,1,1,male,38.00,1,0,19943,90.0000,S,Mr.
225,0,3,male,22.00,0,0,PP 4348,9.3500,S,Mr.
226,1,2,male,19.00,0,0,SW/PP 751,10.5000,S,Mr.
227,0,3,male,20.50,0,0,A/5 21173,7.2500,S,Mr.
228,0,2,male,18.00,0,0,236171,13.0000,S,Mr.
230,1,1,female,35.00,1,0,36973,83.4750,S,Mrs.
231,0,3,male,29.00,0,0,347067,7.7750,S,Mr.
232,0,2,male,59.00,0,0,237442,13.5000,S,Mr.
233,1,3,female,5.00,4,2,347077,31.3875,S,Miss.
234,0,2,male,24.00,0,0,C.A. 29566,10.5000,S,Mr.
236,0,2,male,44.00,1,0,26707,26.0000,S,Mr.
237,1,2,female,8.00,0,2,C.A. 31921,26.2500,S,Miss.
238,0,2,male,19.00,0,0,28665,10.5000,S,Mr.
239,0,2,male,33.00,0,0,SCO/W 1585,12.2750,S,Mr.
242,0,2,male,29.00,0,0,W./C. 14263,10.5000,S,Mr.
243,0,3,male,22.00,0,0,STON/O 2. 3101275,7.1250,S,Mr.
244,0,3,male,30.00,0,0,2694,7.2250,C,Mr.
245,0,1,male,44.00,2,0,19928,90.0000,Q,Dr.
246,0,3,female,25.00,0,0,347071,7.7750,S,Miss.
247,1,2,female,24.00,0,2,250649,14.5000,S,Mrs.
248,1,1,male,37.00,1,1,11751,52.5542,S,Mr.
249,0,2,male,54.00,1,0,244252,26.0000,S,Rev.
251,0,3,female,29.00,1,1,347054,10.4625,S,Mrs.
252,0,1,male,62.00,0,0,113514,26.5500,S,Mr.
253,0,3,male,30.00,1,0,A/5. 3336,16.1000,S,Mr.
254,0,3,female,41.00,0,2,370129,20.2125,S,Mrs.
255,1,3,female,29.00,0,2,2650,15.2458,C,Mrs.
257,1,1,female,30.00,0,0,110152,86.5000,S,Miss.
258,1,1,female,35.00,0,0,PC 17755,512.3292,C,Miss.
259,1,2,female,50.00,0,1,230433,26.0000,S,Mrs.
261,1,3,male,3.00,4,2,347077,31.3875,S,Master.
262,0,1,male,52.00,1,1,110413,79.6500,S,Mr.
263,0,1,male,40.00,0,0,112059,0.0000,S,Mr.
265,0,2,male,36.00,0,0,C.A. 17248,10.5000,S,Mr.
266,0,3,male,16.00,4,1,3101295,39.6875,S,Mr.
267,1,3,male,25.00,1,0,347083,7.7750,S,Mr.
268,1,1,female,58.00,0,1,PC 17582,153.4625,S,Mrs.
269,1,1,female,35.00,0,0,PC 17760,135.6333,S,Miss.
271,1,3,male,25.00,0,0,LINE,0.0000,S,Mr.
272,1,2,female,41.00,0,1,250644,19.5000,S,Mrs.
273,0,1,male,37.00,0,1,PC 17596,29.7000,C,Mr.
275,1,1,female,63.00,1,0,13502,77.9583,S,Miss.
276,0,3,female,45.00,0,0,347073,7.7500,S,Miss.
278,0,3,male,7.00,4,1,382652,29.1250,Q,Master.
279,1,3,female,35.00,1,1,C.A. 2673,20.2500,S,Mrs.
280,0,3,male,65.00,0,0,336439,7.7500,Q,Mr.
281,0,3,male,28.00,0,0,347464,7.8542,S,Mr.
282,0,3,male,16.00,0,0,345778,9.5000,S,Mr.
283,1,3,male,19.00,0,0,A/5. 10482,8.0500,S,Mr.
285,0,3,male,33.00,0,0,349239,8.6625,C,Mr.
286,1,3,male,30.00,0,0,345774,9.5000,S,Mr.
287,0,3,male,22.00,0,0,349206,7.8958,S,Mr.
288,1,2,male,42.00,0,0,237798,13.0000,S,Mr.
289,1,3,female,22.00,0,0,370373,7.7500,Q,Miss.
290,1,1,female,26.00,0,0,19877,78.8500,S,Miss.
291,1,1,female,19.00,1,0,11967,91.0792,C,Mrs.
292,0,2,male,36.00,0,0,SC/Paris 2163,12.8750,C,Mr.
293,0,3,female,24.00,0,0,349236,8.8500,S,Miss.
294,0,3,male,24.00,0,0,349233,7.8958,S,Mr.
296,0,3,male,23.50,0,0,2693,7.2292,C,Mr.
297,0,1,female,2.00,1,2,113781,151.5500,S,Miss.
299,1,1,female,50.00,0,1,PC 17558,247.5208,C,Mrs.
302,0,3,male,19.00,0,0,LINE,0.0000,S,Mr.
305,1,1,male,0.92,1,2,113781,151.5500,S,Master.
307,1,1,female,17.00,1,0,PC 17758,108.9000,C,Mrs.
308,0,2,male,30.00,1,0,P/PP 3381,24.0000,C,Mr.
309,1,1,female,30.00,0,0,PC 17485,56.9292,C,Miss.
310,1,1,female,24.00,0,0,11767,83.1583,C,Miss.
311,1,1,female,18.00,2,2,PC 17608,262.3750,C,Miss.
312,0,2,female,26.00,1,1,250651,26.0000,S,Mrs.
313,0,3,male,28.00,0,0,349243,7.8958,S,Mr.
314,0,2,male,43.00,1,1,F.C.C. 13529,26.2500,S,Mr.
315,1,3,female,26.00,0,0,347470,7.8542,S,Miss.
316,1,2,female,24.00,1,0,244367,26.0000,S,Mrs.
317,0,2,male,54.00,0,0,29011,14.0000,S,Dr.
318,1,1,female,31.00,0,2,36928,164.8667,S,Miss.
319,1,1,female,40.00,1,1,16966,134.5000,C,Mrs.
320,0,3,male,22.00,0,0,A/5 21172,7.2500,S,Mr.
321,0,3,male,27.00,0,0,349219,7.8958,S,Mr.
322,1,2,female,30.00,0,0,234818,12.3500,Q,Miss.
323,1,2,female,22.00,1,1,248738,29.0000,S,Mrs.
325,1,1,female,36.00,0,0,PC 17760,135.6333,C,Miss.
326,0,3,male,61.00,0,0,345364,6.2375,S,Mr.
327,1,2,female,36.00,0,0,28551,13.0000,S,Mrs.
328,1,3,female,31.00,1,1,363291,20.5250,S,Mrs.
329,1,1,female,16.00,0,1,111361,57.9792,C,Miss.
331,0,1,male,45.50,0,0,113043,28.5000,S,Mr.
332,0,1,male,38.00,0,1,PC 17582,153.4625,S,Mr.
333,0,3,male,16.00,2,0,345764,18.0000,S,Mr.
336,0,1,male,29.00,1,0,113776,66.6000,S,Mr.
337,1,1,female,41.00,0,0,16966,134.5000,C,Miss.
338,1,3,male,45.00,0,0,7598,8.0500,S,Mr.
339,0,1,male,45.00,0,0,113784,35.5000,S,Mr.
340,1,2,male,2.00,1,1,230080,26.0000,S,Master.
341,1,1,female,24.00,3,2,19950,263.0000,S,Miss.
342,0,2,male,28.00,0,0,248740,13.0000,S,Mr.
343,0,2,male,25.00,0,0,244361,13.0000,S,Mr.
344,0,2,male,36.00,0,0,229236,13.0000,S,Mr.
345,1,2,female,24.00,0,0,248733,13.0000,S,Miss.
346,1,2,female,40.00,0,0,31418,13.0000,S,Miss.
348,1,3,male,3.00,1,1,C.A. 37671,15.9000,S,Master.
349,0,3,male,42.00,0,0,315088,8.6625,S,Mr.
350,0,3,male,23.00,0,0,7267,9.2250,S,Mr.
352,0,3,male,15.00,1,1,2695,7.2292,C,Mr.
353,0,3,male,25.00,1,0,349237,17.8000,S,Mr.
355,0,3,male,28.00,0,0,345783,9.5000,S,Mr.
356,1,1,female,22.00,0,1,113505,55.0000,S,Miss.
357,0,2,female,38.00,0,0,237671,13.0000,S,Miss.
360,0,3,male,40.00,1,4,347088,27.9000,S,Mr.
361,0,2,male,29.00,1,0,SC/PARIS 2167,27.7208,C,Mr.
362,0,3,female,45.00,0,1,2691,14.4542,C,Mrs.
363,0,3,male,35.00,0,0,SOTON/O.Q. 3101310,7.0500,S,Mr.
365,0,3,male,30.00,0,0,C 7076,7.2500,S,Mr.
366,1,1,female,60.00,1,0,110813,75.2500,C,Mrs.
369,1,1,female,24.00,0,0,PC 17477,69.3000,C,Mme.
370,1,1,male,25.00,1,0,11765,55.4417,C,Mr.
371,0,3,male,18.00,1,0,3101267,6.4958,S,Mr.
372,0,3,male,19.00,0,0,323951,8.0500,S,Mr.
373,0,1,male,22.00,0,0,PC 17760,135.6333,C,Mr.
374,0,3,female,3.00,3,1,349909,21.0750,S,Miss.
376,1,3,female,22.00,0,0,C 7077,7.2500,S,Miss.
377,0,1,male,27.00,0,2,113503,211.5000,C,Mr.
378,0,3,male,20.00,0,0,2648,4.0125,C,Mr.
379,0,3,male,19.00,0,0,347069,7.7750,S,Mr.
380,1,1,female,42.00,0,0,PC 17757,227.5250,C,Miss.
381,1,3,female,1.00,0,2,2653,15.7417,C,Miss.
382,0,3,male,32.00,0,0,STON/O 2. 3101293,7.9250,S,Mr.
383,1,1,female,35.00,1,0,113789,52.0000,S,Mrs.
385,0,2,male,18.00,0,0,S.O.C. 14879,73.5000,S,Mr.
386,0,3,male,1.00,5,2,CA 2144,46.9000,S,Master.
387,1,2,female,36.00,0,0,27849,13.0000,S,Miss.
389,1,2,female,17.00,0,0,SC 1748,12.0000,C,Miss.
390,1,1,male,36.00,1,2,113760,120.0000,S,Mr.
391,1,3,male,21.00,0,0,350034,7.7958,S,Mr.
392,0,3,male,28.00,2,0,3101277,7.9250,S,Mr.
393,1,1,female,23.00,1,0,35273,113.2750,C,Miss.
394,1,3,female,24.00,0,2,PP 9549,16.7000,S,Mrs.
395,0,3,male,22.00,0,0,350052,7.7958,S,Mr.
396,0,3,female,31.00,0,0,350407,7.8542,S,Miss.
397,0,2,male,46.00,0,0,28403,26.0000,S,Mr.
398,0,2,male,23.00,0,0,244278,10.5000,S,Dr.
399,1,2,female,28.00,0,0,240929,12.6500,S,Mrs.
400,1,3,male,39.00,0,0,STON/O 2. 3101289,7.9250,S,Mr.
401,0,3,male,26.00,0,0,341826,8.0500,S,Mr.
402,0,3,female,21.00,1,0,4137,9.8250,S,Miss.
403,0,3,male,28.00,1,0,STON/O2. 3101279,15.8500,S,Mr.
404,0,3,female,20.00,0,0,315096,8.6625,S,Miss.
405,0,2,male,34.00,1,0,28664,21.0000,S,Mr.
406,0,3,male,51.00,0,0,347064,7.7500,S,Mr.
407,1,2,male,3.00,1,1,29106,18.7500,S,Master.
408,0,3,male,21.00,0,0,312992,7.7750,S,Mr.
412,1,1,female,33.00,1,0,19928,90.0000,Q,Miss.
414,1,3,male,44.00,0,0,STON/O 2. 3101269,7.9250,S,Mr.
416,1,2,female,34.00,1,1,28220,32.5000,S,Mrs.
417,1,2,female,18.00,0,2,250652,13.0000,S,Miss.
418,0,2,male,30.00,0,0,28228,13.0000,S,Mr.
419,0,3,female,10.00,0,2,345773,24.1500,S,Miss.
421,0,3,male,21.00,0,0,A/5. 13032,7.7333,Q,Mr.
422,0,3,male,29.00,0,0,315082,7.8750,S,Mr.
423,0,3,female,28.00,1,1,347080,14.4000,S,Mrs.
424,0,3,male,18.00,1,1,370129,20.2125,S,Mr.
426,1,2,female,28.00,1,0,2003,26.0000,S,Mrs.
427,1,2,female,19.00,0,0,250655,26.0000,S,Miss.
429,1,3,male,32.00,0,0,SOTON/O.Q. 392078,8.0500,S,Mr.
430,1,1,male,28.00,0,0,110564,26.5500,S,Mr.
432,1,2,female,42.00,1,0,SC/AH 3085,26.0000,S,Mrs.
433,0,3,male,17.00,0,0,STON/O 2. 3101274,7.1250,S,Mr.
434,0,1,male,50.00,1,0,13507,55.9000,S,Mr.
435,1,1,female,14.00,1,2,113760,120.0000,S,Miss.
436,0,3,female,21.00,2,2,W./C. 6608,34.3750,S,Miss.
437,1,2,female,24.00,2,3,29106,18.7500,S,Mrs.
438,0,1,male,64.00,1,4,19950,263.0000,S,Mr.
439,0,2,male,31.00,0,0,C.A. 18723,10.5000,S,Mr.
440,1,2,female,45.00,1,1,F.C.C. 13529,26.2500,S,Mrs.
441,0,3,male,20.00,0,0,345769,9.5000,S,Mr.
442,0,3,male,25.00,1,0,347076,7.7750,S,Mr.
443,1,2,female,28.00,0,0,230434,13.0000,S,Ms.
445,1,1,male,4.00,0,2,33638,81.8583,S,Master.
446,1,2,female,13.00,0,1,250644,19.5000,S,Miss.
447,1,1,male,34.00,0,0,113794,26.5500,S,Mr.
448,1,3,female,5.00,2,1,2666,19.2583,C,Miss.
449,1,1,male,52.00,0,0,113786,30.5000,S,Major.
450,0,2,male,36.00,1,2,C.A. 34651,27.7500,S,Mr.
452,0,1,male,30.00,0,0,113051,27.7500,C,Mr.
453,1,1,male,49.00,1,0,17453,89.1042,C,Mr.
455,1,3,male,29.00,0,0,349240,7.8958,C,Mr.
456,0,1,male,65.00,0,0,13509,26.5500,S,Mr.
458,1,2,female,50.00,0,0,F.C.C. 13531,10.5000,S,Miss.
460,1,1,male,48.00,0,0,19952,26.5500,S,Mr.
461,0,3,male,34.00,0,0,364506,8.0500,S,Mr.
462,0,1,male,47.00,0,0,111320,38.5000,S,Mr.
463,0,2,male,48.00,0,0,234360,13.0000,S,Mr.
465,0,3,male,38.00,0,0,SOTON/O.Q. 3101306,7.0500,S,Mr.
467,0,1,male,56.00,0,0,113792,26.5500,S,Mr.
469,1,3,female,0.75,2,1,2666,19.2583,C,Miss.
471,0,3,male,38.00,0,0,315089,8.6625,S,Mr.
472,1,2,female,33.00,1,2,C.A. 34651,27.7500,S,Mrs.
473,1,2,female,23.00,0,0,SC/AH Basle 541,13.7917,C,Mrs.
474,0,3,female,22.00,0,0,7553,9.8375,S,Miss.
476,0,2,male,34.00,1,0,31027,21.0000,S,Mr.
477,0,3,male,29.00,1,0,3460,7.0458,S,Mr.
478,0,3,male,22.00,0,0,350060,7.5208,S,Mr.
479,1,3,female,2.00,0,1,3101298,12.2875,S,Miss.
480,0,3,male,9.00,5,2,CA 2144,46.9000,S,Master.
482,0,3,male,50.00,0,0,A/5 3594,8.0500,S,Mr.
483,1,3,female,63.00,0,0,4134,9.5875,S,Mrs.
484,1,1,male,25.00,1,0,11967,91.0792,C,Mr.
486,1,1,female,35.00,1,0,19943,90.0000,S,Mrs.
487,0,1,male,58.00,0,0,11771,29.7000,C,Mr.
488,0,3,male,30.00,0,0,A.5. 18509,8.0500,S,Mr.
489,1,3,male,9.00,1,1,C.A. 37671,15.9000,S,Master.
491,0,3,male,21.00,0,0,SOTON/OQ 3101317,7.2500,S,Mr.
492,0,1,male,55.00,0,0,113787,30.5000,S,Mr.
493,0,1,male,71.00,0,0,PC 17609,49.5042,C,Mr.
494,0,3,male,21.00,0,0,A/4 45380,8.0500,S,Mr.
496,1,1,female,54.00,1,0,36947,78.2667,C,Miss.
498,0,1,female,25.00,1,2,113781,151.5500,S,Mrs.
499,0,3,male,24.00,0,0,350035,7.7958,S,Mr.
500,0,3,male,17.00,0,0,315086,8.6625,S,Mr.
501,0,3,female,21.00,0,0,364846,7.7500,Q,Miss.
503,0,3,female,37.00,0,0,4135,9.5875,S,Miss.
504,1,1,female,16.00,0,0,110152,86.5000,S,Miss.
505,0,1,male,18.00,1,0,PC 17758,108.9000,C,Mr.
506,1,2,female,33.00,0,2,26360,26.0000,S,Mrs.
508,0,3,male,28.00,0,0,C 4001,22.5250,S,Mr.
509,1,3,male,26.00,0,0,1601,56.4958,S,Mr.
510,1,3,male,29.00,0,0,382651,7.7500,Q,Mr.
512,1,1,male,36.00,0,0,PC 17473,26.2875,S,Mr.
513,1,1,female,54.00,1,0,PC 17603,59.4000,C,Mrs.
514,0,3,male,24.00,0,0,349209,7.4958,S,Mr.
515,0,1,male,47.00,0,0,36967,34.0208,S,Mr.
516,1,2,female,34.00,0,0,C.A. 34260,10.5000,S,Mrs.
518,1,2,female,36.00,1,0,226875,26.0000,S,Mrs.
519,0,3,male,32.00,0,0,349242,7.8958,S,Mr.
520,1,1,female,30.00,0,0,12749,93.5000,S,Miss.
521,0,3,male,22.00,0,0,349252,7.8958,S,Mr.
523,1,1,female,44.00,0,1,111361,57.9792,C,Mrs.
525,0,3,male,40.50,0,0,367232,7.7500,Q,Mr.
526,1,2,female,50.00,0,0,W./C. 14258,10.5000,S,Miss.
528,0,3,male,39.00,0,0,3101296,7.9250,S,Mr.
529,0,2,male,23.00,2,1,29104,11.5000,S,Mr.
530,1,2,female,2.00,1,1,26360,26.0000,S,Miss.
532,0,3,male,17.00,1,1,2690,7.2292,C,Mr.
534,0,3,female,30.00,0,0,315084,8.6625,S,Miss.
535,1,2,female,7.00,0,2,F.C.C. 13529,26.2500,S,Miss.
536,0,1,male,45.00,0,0,113050,26.5500,S,Major.
537,1,1,female,30.00,0,0,PC 17761,106.4250,C,Miss.
539,1,1,female,22.00,0,2,13568,49.5000,C,Miss.
540,1,1,female,36.00,0,2,WE/P 5735,71.0000,S,Miss.
541,0,3,female,9.00,4,2,347082,31.2750,S,Miss.
542,0,3,female,11.00,4,2,347082,31.2750,S,Miss.
543,1,2,male,32.00,1,0,2908,26.0000,S,Mr.
544,0,1,male,50.00,1,0,PC 17761,106.4250,C,Mr.
545,0,1,male,64.00,0,0,693,26.0000,S,Mr.

In [21]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  712.000000  712.000000  712.000000  712.000000  712.000000  712.000000
mean     0.404494    2.240169   29.642093    0.514045    0.432584   34.567251
std      0.491139    0.836854   14.492933    0.930692    0.854181   52.938648
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.000000    0.000000    0.000000    8.050000
50%      0.000000    2.000000   28.000000    0.000000    0.000000   15.645850
75%      1.000000    3.000000   38.000000    1.000000    1.000000   33.000000
max      1.000000    3.000000   80.000000    5.000000    6.000000  512.329200